src/Back-end/mysite/mysite/urls.py
from unicodedata import name
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from news.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('restapi/', include('restapi.urls')),

]

urlpatterns += i18n_patterns (
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('news/', include('news.urls')),
    path('', homepage, name='home'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)        # Should we use there append()?

src/Back-end/mysite/news/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('search/', search, name='browse-publications'),
    path('material/', material_info, name='material-info'),
    path('upload/', material_upload, name='material-upload'),
    path('publication/<int:publication_pk>/', view_publication, name='view-publication'),
    path('user/<int:teacher_pk>', view_user, name='view-profile'),
    #     Endpoints:
    path('like_publication/<int:publication_pk>/', like_publication, name='like-publication'),
    path('download_publication_materials/<int:publication_pk>/', download_publication_materials, name='download-publication-materials'),
]

src/Back-end/mysite/news/models.py
from django.db import models
from users.models import Teacher
from django.utils.translation import gettext_lazy as _
from .validators import validate_file_size_25mb
from groups.models import Methodic_group


class Publication(models.Model):
    # ID - Django by default creates it and assigns it as PK
    title = models.CharField(max_length=100, verbose_name='Title')
    language = models.CharField(max_length=20, verbose_name='Language')
    student_year = models.IntegerField(blank=False, verbose_name='Student Year')
    is_public = models.BooleanField(default=True, verbose_name='Is Public?')
    short_description = models.TextField(max_length=140, verbose_name='Short Description')
    description = models.TextField(blank=True, verbose_name='Description')     # change to True if it is possible to post materials only
    media = models.FileField(blank=True, upload_to='publication_materials/%Y/%m/%d', verbose_name=_('Media contents of file (up to 25MB)'), validators=[validate_file_size_25mb])
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')        # To be set only 1 time
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Edited at')             # Automatically updates on change
    photo = models.ImageField(blank=True, upload_to='publication_photos/%Y/%m/%d', verbose_name=_('Publication Photo'))      # Will save picture based on upload date, automatically creates folder
    # = = = = = Many-To_one relationships = = = = =
    creator_id = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='creator_id', verbose_name='Creator')
    related_to_group = models.ForeignKey(Methodic_group, blank=True, null=True, on_delete=models.CASCADE, verbose_name="Related to group")
    subject = models.ForeignKey('Subject', on_delete=models.PROTECT)
    """ If class "Subject" was described before (above class "Publication"), it would be ok to write
            it without quotes 
        PROTECT ensures, that we won't delete Subject that has some publications
            null=True allows us to create Subject for now, otherwise it is required     """
    # = = = = = M2M relationships = = = = =
    likes = models.ManyToManyField(Teacher, blank=True)
    downloads = models.ManyToManyField(Teacher, through='Downloads', related_name='teacher_downloads')
    comments = models.ManyToManyField(Teacher, through='Comments', related_name='commentaries')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Publication"        # Name of your model in single form
        verbose_name_plural = "Publications"        # Name of your model in plural form
        ordering = ['-created_at', 'title', ]         # -created_at prints the newest publications at the top


class Downloads(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='who_downloaded')      # No need to have records with missing teachers
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, related_name='what_downloaded')
    date_downloaded = models.DateTimeField(auto_now=True, verbose_name='Downloaded at')      # Automatically updates on change


class Comments(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='author_of_comment')  # No need to have records with missing teachers
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, related_name='commented_publication')
    comment = models.TextField(verbose_name='Comment')
    comment_date = models.DateTimeField(auto_now_add=True, verbose_name='Commented at')     # To be set only 1 time


class Subject(models.Model):
    # ID - Django by default creates it and assigns it as PK
    name = models.CharField(max_length=30, unique=True, verbose_name="Name of subject")     # Math, History, Lithuanian language

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Subject"        # Name of your model in single form
        verbose_name_plural = "Subjects"        # Name of your model in plural form
        ordering = ['name', ]

src/Back-end/mysite/news/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect, FileResponse
from django.shortcuts import render, redirect

from users.forms import RecommendationForm
from users.models import Teacher, Recommends
from groups.models import Methodic_group, Participates_in
from .forms import UploadFileForm, CommentPublicationForm
from .models import Publication, Subject, Downloads, Comments


def homepage(request):
    list_of_teacher_pks = list(Teacher.objects.values_list('pk', flat=True))

    list_teacher_pk_and_total_no_of_likes = []
    for pk in list_of_teacher_pks:
        total_no_of_likes = Publication.objects.filter(creator_id=pk).values('likes').count()
        list_teacher_pk_and_total_no_of_likes.append([pk, total_no_of_likes])

    list_teacher_pk_and_total_no_of_likes.sort(key=lambda x: x[1], reverse=True)  # Sorts list by total no of likes
    list_teacher_pk_and_total_no_of_likes = list_teacher_pk_and_total_no_of_likes[:3]       # Leave top 3 results

    # Get PKs of top 3 teachers
    get_PKs = lambda: [x[0] for x in list_teacher_pk_and_total_no_of_likes]
    pks_of_top_teachers = get_PKs()

    # Get top teachers
    teacher_dictionaries = list(Teacher.objects.filter(pk__in=pks_of_top_teachers).values('pk', 'profile_picture', 'full_name', 'profession', 'self_description', ))

    # = = = Get top publications = = =
    publication_pks = list(Publication.objects.values_list('pk', flat=True))

    list_publication_pk_and_total_no_of_likes = []
    for pk in publication_pks:
        publication_likes = Publication.objects.get(pk=pk).likes.count()
        list_publication_pk_and_total_no_of_likes.append([pk, publication_likes])

    list_publication_pk_and_total_no_of_likes.sort(key=lambda x: x[1], reverse=True)  # Sorts list by no of likes
    list_publication_pk_and_total_no_of_likes = list_publication_pk_and_total_no_of_likes[:3]       # Leave top 3 results

    publication_dictionaries = []

    for pk, no_of_likes in list_publication_pk_and_total_no_of_likes:
        publication = Publication.objects.filter(pk=pk).values('pk', 'photo', 'creator_id', 'title', 'subject', 'student_year', 'language', 'short_description')
        publication = publication[0]
        author = Teacher.objects.get(pk=publication.get('creator_id')).full_name
        subject_name = Subject.objects.get(pk=publication.get('subject')).name
        publication.update({
            'author': author,
            'subject': subject_name,
            'likes': no_of_likes,
        })
        publication_dictionaries.append(publication)

    context = {
        'teachers': teacher_dictionaries,
        'publications': publication_dictionaries,
    }

    return render(request, "news/homepage.html", context=context)


@login_required
def material_info(request):
    return render(request, "news/material.html")


def convert_publication_to_dictionary(pub):
    publication_dictionary = {
        "pk": pub.pk,
        "photo": pub.photo,
        "author_name": pub.creator_id.full_name,
        "author_pk": pub.creator_id.pk,
        "title": pub.title,
        "subject": pub.subject.name,
        "student_year": pub.student_year,
        "language": pub.language,
        "short_description": pub.short_description,
        "likes": pub.likes.count(),
    }
    return publication_dictionary


def get_dictionary_of_subjects(selected_subject=None):
    # TODO: review possibility of retrieving only subjects which have associated publications
    #   to do that - take a look how languages are retrieved in get_dictionary_of_languages()
    subject_list = list(Subject.objects.values_list('name', flat=True).order_by('name'))
    subject_dictionaries = []

    for subject in subject_list:
        subject_dictionaries.append({
            'name': subject,
            'is_selected': False,
        })
    if selected_subject:    # If subject is selected, set its selection in HTML as active
        selected_subject_index = subject_list.index(selected_subject)
        subject_to_set_selection = subject_dictionaries[selected_subject_index]
        subject_to_set_selection.update({'is_selected': True, })
        subject_dictionaries[selected_subject_index] = subject_to_set_selection

    return subject_dictionaries


def get_dictionary_of_languages(selected_language=None):
    languages = list(Publication.objects.values_list('language', flat=True).order_by('language').distinct())
    language_dictionaries = []

    for language in languages:
        language_dictionaries.append({
            'name': language,
            'is_selected': False,
        })
    if selected_language:
        selected_language_index = languages.index(selected_language)
        language_to_set_selection = language_dictionaries[selected_language_index]
        language_to_set_selection.update({'is_selected': True, })
        language_dictionaries[selected_language_index] = language_to_set_selection

    return language_dictionaries


def get_dictionary_of_grades(selected_grade=None):
    grades = list(Publication.objects.values_list('student_year', flat=True).order_by('student_year').distinct())
    grade_dictionaries = []

    for grade in grades:
        grade_dictionaries.append({
            'name': grade,
            'is_selected': False,
        })
    if selected_grade:
        selected_grade = int(selected_grade)
        selected_grade_index = grades.index(selected_grade)
        grade_to_set_selection = grade_dictionaries[selected_grade_index]
        grade_to_set_selection.update({'is_selected': True, })
        grade_dictionaries[selected_grade_index] = grade_to_set_selection

    return grade_dictionaries


def search(request):
    sort_options = [
        {'name': 'Alphabetically A-Z', 'selected': False},
        {'name': 'Alphabetically Z-A', 'selected': False},
        {'name': 'Newest First', 'selected': False},
        {'name': 'Oldest First', 'selected': False},
        {'name': 'Likes', 'selected': False},
    ]

    if request.method == 'POST':
        search_keywords = request.POST['search_keywords']
        search_sort = request.POST['search_sort']
        search_subject = request.POST.get('search_subject')
        search_grade = request.POST.get('search_grade')
        search_language = request.POST.get('search_language')
        search_group = request.POST.get('search_group')

        # print('\n\n|+| Your searched something with POST:', search_keywords,
        #       '\n|+| Sort by:', search_sort,
        #       '\n|+| Filters:', search_subject, search_grade, search_language, search_group,
        #       '\n\n')
        publications_objects = Publication.objects.filter(title__icontains=search_keywords)

        subjects = get_dictionary_of_subjects(selected_subject=search_subject)
        languages = get_dictionary_of_languages(selected_language=search_language)
        grades = get_dictionary_of_grades(selected_grade=search_grade)

        # Applying sorting
        if search_sort == 'Alphabetically A-Z':
            publications_objects = publications_objects.order_by('title')
            sort_options[0] = {'name': 'Alphabetically A-Z', 'selected': True}

        if search_sort == 'Alphabetically Z-A':
            publications_objects = publications_objects.order_by('-title')
            sort_options[1] = {'name': 'Alphabetically Z-A', 'selected': True}

        if search_sort == 'Newest First':
            publications_objects = publications_objects.order_by('-created_at')
            sort_options[2] = {'name': 'Newest First', 'selected': True}

        if search_sort == 'Oldest First':
            publications_objects = publications_objects.order_by('created_at')
            sort_options[3] = {'name': 'Oldest First', 'selected': True}

        if search_sort == 'Likes':
            publications_objects = publications_objects.order_by('-likes')
            sort_options[4] = {'name': 'Likes', 'selected': True}

        # Filtering by subject
        if search_subject:
            search_subject = Subject.objects.get(name=search_subject)
            publications_objects = publications_objects.filter(subject=search_subject)

        # Filtering by grade
        if search_grade:
            publications_objects = publications_objects.filter(student_year=search_grade)

        # Filtering based on language
        if search_language:
            publications_objects = publications_objects.filter(language=search_language)

        # Filtering based on group
        if search_group:
            publications_objects = publications_objects.filter(related_to_group=Methodic_group.objects.get(pk=int(search_group)))

        publications_list = []
        for pub in publications_objects:
            publications_list.append(convert_publication_to_dictionary(pub))

        paginator = Paginator(publications_list, 10000)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)




    else:
        publications_objects = Publication.objects.all()
        subjects = get_dictionary_of_subjects()
        languages = get_dictionary_of_languages()
        grades = get_dictionary_of_grades()

        publications_list = []
        for pub in publications_objects:
            publications_list.append(convert_publication_to_dictionary(pub))

        paginator = Paginator(publications_list, 12)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)


    pks_of_groups_with_publications = Publication.objects.exclude(related_to_group=None).values_list('related_to_group', flat=True)
    pks_of_groups_with_publications = list(dict.fromkeys(pks_of_groups_with_publications))

    context = {
        "publications": page_obj,
        'grades': grades,
        'languages': languages,
        'sort_options': sort_options,
        'subjects': subjects,

src/Back-end/mysite/news/templates/news/basic.html
{% extends 'base.html' %}
{% block contents %}
    <div class="card p-3 py-4">
        <div class="input-group">
            Salam aleikum
        </div>
    </div>
{% endblock %}

src/Back-end/mysite/news/templates/news/homepage.html
{% extends 'home_base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}
{% load i18n %}
{% block contents %}


<main class="main">
    <!-- Front image/desc start -->
    <section class="spotlight bg-cover bg-size--cover"
             style="background-image: url({% static 'images/stormtest.jpg' %})">
        <span class="mask bg-primary alpha-4"></span>
        <div class="spotlight-holder py-sm pt-lg-lg">
            <div class="container d-flex align-items-center">
                <div class="row cols-xs-space cols-sm-space cols-md-space align-items-center justify-content-around">
                    <div class="col-lg-5 text-center">
                        <h2 class="heading h1 text-white strong-400">
                            {% trans "Want to find some materials for your lessons? Yes you do!" %} <!-- Change later -->
                        </h2>
                        <p class="lead text-white mt-4">
                            {% trans "STorm lets you easily and intuitively find and share new learning materials with other teachers!" %}
                            <!-- Change later -->
                        </p>
                    </div>
                    <div class="col-lg-5">
                        <div class="position-relative">
                            <img src="{% static 'images/logo.png' %}" class="img-center img-fluid rounded">
                            <!-- temporary image, replace with screenshot later -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- Front image/desc end -->

    <section class="slice slice-lg" data-delimiter="1">
        <div class="container">
            <div class="row-wrapper">
                <div class="row cols-xs-space cols-sm-space cols-md-space">
                    <div class="col-lg-4">
                        <div class="">
                            <div class="icon text-primary mb-3">
                                <i class="fas fa-book"></i>
                            </div>
                            <h5 class="heading h5">{% trans "Find Content for Lessons" %}</h5>
                            <p>{% trans "It has never been easier, enough endless searching for new quizzes, presentations, tasks or tests, everything is here in one place." %}</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="">
                            <div class="icon text-primary mb-3">
                                <i class="fas fa-thumbs-up"></i>
                            </div>
                            <h5 class="heading h5">{% trans "Help Your Career" %}</h5>
                            <p>{% trans "If you are a new teacher, improve your CV by uploading your own created learning materials and getting ratings and recommendations from other teachers." %}</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="">
                            <div class="icon text-primary mb-3">
                                <i class="fa fa-check"></i>
                            </div>
                            <h5 class="heading h5">{% trans "Completely Free" %}</h5>
                            <p>{% trans "The system is developed with no intentions of monetization and our team focuses heavily on listening to the needs and requests of teachers utilizing our system." %}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="slice slice-lg" data-delimiter="1">
        <div class="container">
            <div class="row cols-xs-space cols-sm-space align-items-center">
                <div class="col-md-6">
                    <img src="{% static 'images/prv/img-1-1000x900.jpg' %}" class="img-center img-fluid rounded z-depth-3">
                </div>
                <div class="col-md-6 col-lg-5 ml-lg-auto">
                    <div class="pr-md-4">
                        <h3 class="heading h3">
                            {% trans "Represent Yourself" %}
                        </h3>
                        <p class="lead text-gray mt-4">{% trans "We offer seemless profile customization to best showcase yourself to the public, including ability to easily link to your social media and linkedin profiles." %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="slice slice-lg" data-delimiter="1">
        <div class="container">
            <div class="mb-md text-center">
                <h3 class="heading h3">{% trans "Active Community of Teachers" %}</h3>
                <div class="fluid-paragraph text-center mt-4">
                    <p class="lead lh-180">{% trans "With some of the best learning content creators!" %}</p>
                </div>
            </div>
            <div class="row cols-xs-space cols-sm-space cols-md-space">
<!--                Cards with top teachers start here -->
                {% for teacher in teachers %}
                <div class="col-lg-4">
                    <div class="card">
                        {% if teacher.profile_picture %}
                            <img src="/media/{{ teacher.profile_picture }}" class="card-img-top" height="275vw" onerror="this.src='{% static 'images/basic.jpg' %}">
                        {% else %}
                            <img src="{% static 'images/basic.jpg' %}" class="card-img-top" height="275vw" onerror="this.src='{% static 'images/user.jpg' %}'">
                        {% endif %}
                        <div class="card-body text-center">
                            <h3 class="heading h5 mb-1">
                                <span class="d-block">{{ teacher.full_name }}</span>
                                {% if teacher.profession %}
                                    <small class="text-muted">{{ teacher.profession }}</small>
                                {% else %}
                                    <small class="text-muted">{%trans "New Teacher" %}</small>
                                {% endif %}
                            </h3>
                            {% if teacher.self_description %}
                                <p class="mt-2">{{ teacher.self_description|truncatewords:12 }}</p>
                            {% else %}
                                </br></br>
                            {% endif %}
                            <a  href="{% url 'view-profile' teacher.pk %}" target="_blank" class="btn btn-sm btn-primary">{% trans "View Profile" %}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
<!--                Cards with top teachers end here -->
            </div>
        </div>
    </section>


    <section class="slice slice-xl" data-delimiter="1">
        <div class="container">
            <div class="row cols-xs-space cols-sm-space align-items-center">
                <div class="col-md-6 order-md-2 ml-lg-auto">
                    <img src="{% static 'images/prv/img-2-1000x900.jpg' %}" class="img-center img-fluid rounded z-depth-3">
                </div>
                <div class="col-md-6 col-lg-5 order-md-1">
                    <div class="pr-md-4">
                        <h3 class="heading h3">
                            {% trans "Easy and Intuitive Material Search" %}
                        </h3>
                        <p class="lead text-gray mt-4">{% trans "With the centralization of learning content sharing in one place, new filtering and search systems finding new materials has never been easier. We strive to provide the best experience for teachers." %}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="slice slice-lg" data-delimiter="1">
        <div class="container">
            <div class="mb-md text-center">
                <h3 class="heading h3">{% trans "Featured Materials"%}</h3>
            </div>
            <div class="row cols-xs-space cols-sm-space cols-md-space">

                <!-- Top materials start here -->
                {% for publication in publications %}
                <div class="col-lg-4">
                    <div class="card">
<!--                        <img src="../assets/images/basic.jpg" class="card-img-top" height="225vw" onerror="this.src='{% static 'images/basic.jpg' %}'">-->
                        {% if publication.photo %}
                            <img src="/media/{{ publication.photo }}" class="card-img-top" height="275vw" onerror="this.src='{% static 'images/basic.jpg' %}'">
                        {% else %}
                            <img src="{% static 'images/basic.jpg' %}" class="card-img-top" height="275vw" onerror="this.src='{% static 'images/user.jpg' %}'">
                        {% endif %}
                        <div class="card-body text-center">
                            <a href="url"><small class="text-muted">{{ publication.author }}</small></a>
                            <h3 class="heading h5 mb-1">
                                <span class="d-block">{{ publication.title }}</span>
                            </h3>
                            <span class="badge badge-lg badge-pill badge-secondary text-uppercase">{{ publication.subject }}</span>
                            <span class="badge badge-lg badge-pill badge-secondary text-uppercase">{% trans "Grade" %} {{ publication.student_year }}</span>
                            <span class="badge badge-lg badge-pill badge-secondary text-uppercase">{{ publication.language }}</span>
                            <br>
                            <p class="mt-2">{{ publication.short_description }}</p>
                            <div class="btn-group btn-action-label" role="group" aria-label="Like">
                                <a href="#" class="btn btn-sm btn-outline-danger btn-label">{{ publication.likes }}</a>
                                <button type="button" class="btn btn-sm btn-danger btn-action">
                                    <i class="fas fa-heart"></i>
                                </button>
                            </div>
                            <a  href="{% url 'view-publication' publication.pk %}" target="_blank"
                                class="btn btn-sm btn-primary">{% trans "View Material" %}</a> <br> <br>
                        </div>
                    </div>
                    <br>
                </div>
                {% endfor %}
                <!-- Top materials end here -->
    </section>
</main>

{% endblock %}

src/Back-end/mysite/news/templates/news/upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    Material upload
{% endblock %}
{% load i18n %}

{% block contents %}

{% if error %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Publication information did not validate:</strong> Please ensure all mandatory fields are filled and file size limits are not exceeded.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}


  <main class="main">
      <form method="POST" class="post-form" enctype="multipart/form-data">
          {% csrf_token %}
    <div class="container mt-2 mb-2">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12">
          <div class="card p-3 py-4" style="border: 2px solid #E8F2FF; box-shadow: 0 8px 17px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)">
            <span class="badge badge-lg badge-pill badge-secondary mb-4">
              <h1>{% trans "Material Upload" %}</h1>
                {% if user.is_authenticated %}
<!--                    <h2>Welcome, {{user.full_name}}</h2>-->
            </span>
                  <div class="input-group mb-3">
                {{form.title}}
            </div>
            <div class="row mb-4">
              <div class="col-md-3">
                {{form.subject}}
              </div>
              <div class="col-md-2">
                  {{form.student_year}}
              </div>
              <div class="col-md-3">
                {{form.language}}
              </div>
              <div class="col-md-3">
                <select name="related_to_group" class="selectpicker" title="Group" placeholder="Group"
                        data-live-search="true" data-live-search-placeholder="Search for a group"
                        id="id_related_to_group">
                  {% for group in available_groups %}
                    <option value="{{ group.pk }}">{{ group.name }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-1">
                <label class="d-block">{% trans "Public" %}</label>
                <label class="toggle-switch">
                  {{form.is_public}}
                  <span class="toggle-switch-slider rounded-circle"></span>
                </label>
              </div>
            </div>
            <div>
                {{form.media|as_crispy_field}}
                {{form.photo|as_crispy_field}}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container mt-4">
      <div class="row d-flex justify-content-center">
        <div class="col-md-5">
          <div class="card p-4" style="border: 2px solid #E8F2FF; box-shadow: 0 8px 17px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)">
            <span class="badge badge-lg badge-pill badge-secondary mb-4">
              <h2>{% trans "Short Description" %}</h2>
            </span>
            <div class="form-group">
              {{form.short_description}}
            </div>
          </div>
        </div>
        <div class="col-md-7">
          <div class="card p-4" style="border: 2px solid #E8F2FF; box-shadow: 0 8px 17px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)">
            <span class="badge badge-lg badge-pill badge-secondary mb-4">
              <h2>{% trans "Full Description" %}</h2>
            </span>
            <div class="form-group">
              {{form.description}}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container mt-4">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12">
          <div class="card p-3 py-4" style="border: 2px solid #E8F2FF; box-shadow: 0 8px 17px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)">
            <div class="col-lg-13">
              <button type="submit" class="btn btn-block btn-primary">
                <p class="h2 text-white">{% trans "Submit" %}</p>
              </button>
                  {% else %}
                    <h2>{% trans "You must login in order to upload!" %}</h2>
                    {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div> <br> <br>
       </form>
  </main>

  {% endblock %}